package com.xworkz.collections.boot;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;

public class DamsInIndia {

	public static void main(String[] args) {
		
		

				Collection<String> damsOfKarntaka = new ArrayList<String>();
				damsOfKarntaka.add("Almatti");
				damsOfKarntaka.add("Basava Sagara(Narayanpur)");
				damsOfKarntaka.add("Raja Lakhamagowda");
				damsOfKarntaka.add("Renuka Sagara");
				damsOfKarntaka.add("Vani Vilasa Sagara");
				damsOfKarntaka.add("Upper Tunga");
				damsOfKarntaka.add("Bhadra");
				damsOfKarntaka.add("Tungabhadra");
				damsOfKarntaka.add("Hemavathi Reservoir");
				damsOfKarntaka.add("Kabini Reservoir");
				damsOfKarntaka.add("Harangi Reservoir");
				damsOfKarntaka.add("Krishna Raja Sagara");
				damsOfKarntaka.add("Linganamakki");
				damsOfKarntaka.add("Chakra Reservoir");
				damsOfKarntaka.add("Savehaklu Reservoir");
				damsOfKarntaka.add("Mani Reservoir");
				damsOfKarntaka.add("Supa");
				damsOfKarntaka.add("Kodasalli");
				damsOfKarntaka.add("Kadra");
				damsOfKarntaka.add("Shanti Sagara");
				damsOfKarntaka.add("Karanja");

				Collection<String> damsOfAndhraPradesh = new ArrayList<String>();// 129s
				damsOfAndhraPradesh.add("Ahobilam / Penna Ahobilam (Dr. K.S.P.A.B.R.)");
				damsOfAndhraPradesh.add("Akkapalem");
				damsOfAndhraPradesh.add("Alaganoor");
				damsOfAndhraPradesh.add("Ananthasagarm");
				damsOfAndhraPradesh.add("Andhra");
				damsOfAndhraPradesh.add("Arniar");
				damsOfAndhraPradesh.add("Bahuda");
				damsOfAndhraPradesh.add("Bhairavanithippa");
				damsOfAndhraPradesh.add("Bhupathipalem");
				damsOfAndhraPradesh.add("Buggavagu");
				damsOfAndhraPradesh.add("Buggavanka");
				damsOfAndhraPradesh.add("Bukkapatnam");
				damsOfAndhraPradesh.add("Chagallu Barrage");
				damsOfAndhraPradesh.add("Cheyyeru / Annamayya");
				damsOfAndhraPradesh.add("Chinnarayaswamy Gudi /Chennaraya");
				damsOfAndhraPradesh.add("Chintakuntavagu");
				damsOfAndhraPradesh.add("Chitravathi");
				damsOfAndhraPradesh.add("Cumbum");
				damsOfAndhraPradesh.add("Dharmavaram");
				damsOfAndhraPradesh.add("Donkarai ( S.H.E.S)");
				damsOfAndhraPradesh.add("Eguva Thamballa Palli - Cheruvu");
				damsOfAndhraPradesh.add("Forebay Lower Sileru ( S.H.E.S)");
				damsOfAndhraPradesh.add("Gajuladinne (Sanjeevaiah Sagar)");
				damsOfAndhraPradesh.add("Ahobilam / Penna Ahobilam (Dr. K.S.P.A.B.R.)");
				damsOfAndhraPradesh.add("Gandicheruvu (Dist-Prakasam)");
				damsOfAndhraPradesh.add("Gandipalem /Pcr Gandipalem");
				damsOfAndhraPradesh.add("Ghambiramgedda");
				damsOfAndhraPradesh.add("Gooty Tank");
				damsOfAndhraPradesh.add("Gorakallu");
				damsOfAndhraPradesh.add("Gundlakamma");
				damsOfAndhraPradesh.add("Gundlamotu	");
				damsOfAndhraPradesh.add("Guntawada Main");
				damsOfAndhraPradesh.add("Haresamudram Big");
				damsOfAndhraPradesh.add("Hiramandalam");
				damsOfAndhraPradesh.add("Jajigedda");
				damsOfAndhraPradesh.add("Jalakanur");
				damsOfAndhraPradesh.add("Jalleru");
				damsOfAndhraPradesh.add("Jhanjhavathi / Janjavathi");
				damsOfAndhraPradesh.add("Kakarla");
				damsOfAndhraPradesh.add("Kalangi");
				damsOfAndhraPradesh.add("Kalinga Dal");
				damsOfAndhraPradesh.add("Kalyani");
				damsOfAndhraPradesh.add("Kampasamudram New");
				damsOfAndhraPradesh.add("Kandaleru /Kandaleru");
				damsOfAndhraPradesh.add("Kanelal Tank");
				damsOfAndhraPradesh.add("Kanigiri");
				damsOfAndhraPradesh.add("Konam");
				damsOfAndhraPradesh.add("Kovvadakalva");
				damsOfAndhraPradesh.add("Krishnapuram (Chittor)");
				damsOfAndhraPradesh.add("Kumili");
				damsOfAndhraPradesh.add("Kushavathi");
				damsOfAndhraPradesh.add("Lower Sagileru");
				damsOfAndhraPradesh.add("Madakasira");
				damsOfAndhraPradesh.add("Maddigedda");
				damsOfAndhraPradesh.add("Madduvalasa");
				damsOfAndhraPradesh.add("Mallimadugu");
				damsOfAndhraPradesh.add("Marala");
				damsOfAndhraPradesh.add("Matchukota Balancing Reservoir");
				damsOfAndhraPradesh.add("Midpennar Stage-I/Mid-Pennar");
				damsOfAndhraPradesh.add("Mopadu");
				damsOfAndhraPradesh.add("Muraripalli / Mararipalli");
				damsOfAndhraPradesh.add("Musurumilli /Musurmilli");
				damsOfAndhraPradesh.add("Mylavaram");
				damsOfAndhraPradesh.add("N.T.R. , Thatiparthi(V), Madugula (M)");
				damsOfAndhraPradesh.add("Nagurur");
				damsOfAndhraPradesh.add("Nakkalagandi");
				damsOfAndhraPradesh.add("Narayanapuram");
				damsOfAndhraPradesh.add("Nellore");
				damsOfAndhraPradesh.add("P.T.Cheruvu");
				damsOfAndhraPradesh.add("Paleru ,Owk");
				damsOfAndhraPradesh.add("Pampa");
				damsOfAndhraPradesh.add("Panthulu Cheruvu");
				damsOfAndhraPradesh.add("Paya Cheruvu");
				damsOfAndhraPradesh.add("Pedaballi");
				damsOfAndhraPradesh.add("Pedda Cheruvu , Nagasamudram");
				damsOfAndhraPradesh.add("Pedda Rayala Cheruvu");
				damsOfAndhraPradesh.add("Peddabadava, Tulasikrishan	");
				damsOfAndhraPradesh.add("Peddagedda");
				damsOfAndhraPradesh.add("Peddayetivanka, Annupal");
				damsOfAndhraPradesh.add("Pedderu");
				damsOfAndhraPradesh.add("Pendekallu");
				damsOfAndhraPradesh.add("Pendlur");
				damsOfAndhraPradesh.add("Peruru");
				damsOfAndhraPradesh.add("Pincha");
				damsOfAndhraPradesh.add("Pittakayagulla");
				damsOfAndhraPradesh.add("Polavaram");
				damsOfAndhraPradesh.add("Pulichintala");
				damsOfAndhraPradesh.add("Raiwada");
				damsOfAndhraPradesh.add("Rallapadu");
				damsOfAndhraPradesh.add("Ramathirtham");
				damsOfAndhraPradesh.add("Rayalacheruvu");
				damsOfAndhraPradesh.add("SPVBS");
				damsOfAndhraPradesh.add("Sadasivakona");
				damsOfAndhraPradesh.add("Sancherla");
				damsOfAndhraPradesh.add("Sankarayalapeta");
				damsOfAndhraPradesh.add("Savisettipalli");
				damsOfAndhraPradesh.add("Seethai Cheru, Seethaipally");
				damsOfAndhraPradesh.add("Siddalagandi");
				damsOfAndhraPradesh.add("Somasila");
				damsOfAndhraPradesh.add("Sreerangarayani Cheruvu");
				damsOfAndhraPradesh.add("Sri Subbaraya Sagar");
				damsOfAndhraPradesh.add("Sri Tenneti Viswanatham Pedderu");
				damsOfAndhraPradesh.add("Surampalem");
				damsOfAndhraPradesh.add("T.Sundupalli");
				damsOfAndhraPradesh.add("Tajangi , Tajangi(V)");
				damsOfAndhraPradesh.add("Thadukuvagu");
				damsOfAndhraPradesh.add("Thammileru");
				damsOfAndhraPradesh.add("Thandava(Sri Raja Sagi Suryanarayana Raju (Srssr)");
				damsOfAndhraPradesh.add("Thatipudi");
				damsOfAndhraPradesh.add("Thippayapalem");
				damsOfAndhraPradesh.add("Turimella Reservoir");
				damsOfAndhraPradesh.add("Upper Pennar");
				damsOfAndhraPradesh.add("Urakagedda , Sankaram (V), Madugula(M)");
				damsOfAndhraPradesh.add("Vanaka Badigedda");
				damsOfAndhraPradesh.add("Varadaraja Swamy Gudi");
				damsOfAndhraPradesh.add("Varaha");
				damsOfAndhraPradesh.add("Varikunta");
				damsOfAndhraPradesh.add("Veligallu");
				damsOfAndhraPradesh.add("Veligonda");
				damsOfAndhraPradesh.add("Velugodu");
				damsOfAndhraPradesh.add("Vengalaraya Sagar");
				damsOfAndhraPradesh.add("Vottigadda");
				damsOfAndhraPradesh.add("Vyasasamudram");
				damsOfAndhraPradesh.add("Y.T.Cheruvu");
				damsOfAndhraPradesh.add("Yeddula Eswaraiah GandiKoata");
				damsOfAndhraPradesh.add("Yeleru");
				damsOfAndhraPradesh.add("Yerrakalva");
				damsOfAndhraPradesh.add("Yogivemana");
				damsOfAndhraPradesh.add("Zurreru");

				Collection<String> damsOfArunachalPradesh = new ArrayList<String>();
				damsOfArunachalPradesh.add("Ranganadi");
				damsOfArunachalPradesh.add("Subansiri Lower HE (Nhpc)");

				Collection<String> damsOfAssam = new ArrayList<String>();
				damsOfAssam.add("Karbi Langpi");
				damsOfAssam.add("Umrong");

				Collection<String> damsOfBihar = new ArrayList<String>();// 129s
				damsOfBihar.add("Ajan");
				damsOfBihar.add("Amrity");
				damsOfBihar.add("Badua");
				damsOfBihar.add("Barnar");
				damsOfBihar.add("Baskund");
				damsOfBihar.add("Belharna");
				damsOfBihar.add("Bilasi");
				damsOfBihar.add("Chandan");
				damsOfBihar.add("Durgawati");
				damsOfBihar.add("Gaighat");
				damsOfBihar.add("Jalkund");
				damsOfBihar.add("Job");
				damsOfBihar.add("Kailash Ghati");
				damsOfBihar.add("Khargpur Lake");
				damsOfBihar.add("Kohira");
				damsOfBihar.add("Kolmahadeo");
				damsOfBihar.add("Morwy");
				damsOfBihar.add("Nagi");
				damsOfBihar.add("Nakti (damsOfBihar)");
				damsOfBihar.add("Phulwaria");
				damsOfBihar.add("Sindhwarni	");
				damsOfBihar.add("Srikhandi");
				damsOfBihar.add("Upper Kiul");

				Collection<String> damsOfChattisgarh = new ArrayList<String>();// 129s
				damsOfChattisgarh.add("Hasdeo Bango (Minimata)");
				damsOfChattisgarh.add("Agariya");
				damsOfChattisgarh.add("Adpather");
				damsOfChattisgarh.add("Ajabnagar");
				damsOfChattisgarh.add("Amabeda");
				damsOfChattisgarh.add("Amachuwa");
				damsOfChattisgarh.add("Amakhokhra");
				damsOfChattisgarh.add("Amakoni");
				damsOfChattisgarh.add("Amgaon");
				damsOfChattisgarh.add("Amhar");
				damsOfChattisgarh.add("Aondhi");
				damsOfChattisgarh.add("Auramimunda");
				damsOfChattisgarh.add("Ayabhandha");
				damsOfChattisgarh.add("Badauli");
				damsOfChattisgarh.add("Badesathi");
				damsOfChattisgarh.add("Badra");
				damsOfChattisgarh.add("Badrika Ashram");
				damsOfChattisgarh.add("Ballar");
				damsOfChattisgarh.add("Banjaridand");
				damsOfChattisgarh.add("Banki");
				damsOfChattisgarh.add("Bankipur");
				damsOfChattisgarh.add("Barat Sagar");
				damsOfChattisgarh.add("Bardar");
				damsOfChattisgarh.add("Barkela");
				damsOfChattisgarh.add("Barnai");
				damsOfChattisgarh.add("Barota");
				damsOfChattisgarh.add("Barpara");
				damsOfChattisgarh.add("Batra");
				damsOfChattisgarh.add("Beherakhar (Banjar )");
				damsOfChattisgarh.add("Belbehra");
				damsOfChattisgarh.add("Belhari");
				damsOfChattisgarh.add("Bhagwantola");
				damsOfChattisgarh.add("Bhopali");
				damsOfChattisgarh.add("Bhoramdeo");
				damsOfChattisgarh.add("Bhortola");
				damsOfChattisgarh.add("Bhulsi");
				damsOfChattisgarh.add("Bhursatoli");
				damsOfChattisgarh.add("Binjali");
				damsOfChattisgarh.add("Bisrampuri");
				damsOfChattisgarh.add("Bordi");
				damsOfChattisgarh.add("Chaker");
				damsOfChattisgarh.add("Chamat");
				damsOfChattisgarh.add("Champi");
				damsOfChattisgarh.add("Chandra Nagar");
				damsOfChattisgarh.add("Chanti");
				damsOfChattisgarh.add("Charcha");
				damsOfChattisgarh.add("Charpara");
				damsOfChattisgarh.add("Chhirpani");
				damsOfChattisgarh.add("Chhota Palgi");
				damsOfChattisgarh.add("Chhuwari Pali");
				damsOfChattisgarh.add("Chikhali");
				damsOfChattisgarh.add("Chilputi");
				damsOfChattisgarh.add("Chiniya");
				damsOfChattisgarh.add("Chourasiya");
				damsOfChattisgarh.add("Churiyapat");
				damsOfChattisgarh.add("Dandgaon");
				damsOfChattisgarh.add("Darki");
				damsOfChattisgarh.add("Darritola");
				damsOfChattisgarh.add("Deogaon");
				damsOfChattisgarh.add("Deokatta");
				damsOfChattisgarh.add("Deoripali");
				damsOfChattisgarh.add("Dhab");
				damsOfChattisgarh.add("Dhamni No. I");
				damsOfChattisgarh.add("Dhanras");
				damsOfChattisgarh.add("Dhara");
				damsOfChattisgarh.add("Dhawanpur");
				damsOfChattisgarh.add("Dhupkot");
				damsOfChattisgarh.add("Diona");
				damsOfChattisgarh.add("Doura");
				damsOfChattisgarh.add("Dudhawa");
				damsOfChattisgarh.add("Fatehpur");
				damsOfChattisgarh.add("Fulwari");
				damsOfChattisgarh.add("Gagnai");
				damsOfChattisgarh.add("Ganeshpur");
				damsOfChattisgarh.add("Gangpur");
				damsOfChattisgarh.add("Ganiyari");
				damsOfChattisgarh.add("Gatatola");
				damsOfChattisgarh.add("Gej");
				damsOfChattisgarh.add("Ghatoi");
				damsOfChattisgarh.add("Ghoghra");
				damsOfChattisgarh.add("Ghongha");
				damsOfChattisgarh.add("Ghughwa");
				damsOfChattisgarh.add("Ghumarapadar");
				damsOfChattisgarh.add("Ghunghutta");
				damsOfChattisgarh.add("Gobari");
				damsOfChattisgarh.add("Gondli");
				damsOfChattisgarh.add("Gouri");
				damsOfChattisgarh.add("Gunderdehi");
				damsOfChattisgarh.add("Gursia");
				damsOfChattisgarh.add("Hathlewa");
				damsOfChattisgarh.add("Jagannathpur");
				damsOfChattisgarh.add("Jagatpur");
				damsOfChattisgarh.add("Jamdih");
				damsOfChattisgarh.add("Jhalpi");
				damsOfChattisgarh.add("Jhingo");
				damsOfChattisgarh.add("Jhumka");
				damsOfChattisgarh.add("Junwani");
				damsOfChattisgarh.add("Kachhod");
				damsOfChattisgarh.add("Kadna");
				damsOfChattisgarh.add("Kalidaraha");

				Collection<String> damsOfGoa = new ArrayList<String>();
				damsOfGoa.add("Anjunam");
				damsOfGoa.add("M.I");
				damsOfGoa.add("Salaulim");

				Collection<String> damsOfHaryana = new ArrayList<String>();
				damsOfHaryana.add("kaushalya");

				Collection<String> damsOfHimachalPradesh = new ArrayList<String>();
				damsOfHimachalPradesh.add("Baira Siul");
				damsOfHimachalPradesh.add("Bassi");
				damsOfHimachalPradesh.add("Bhakra");
				damsOfHimachalPradesh.add("Chamera");
				damsOfHimachalPradesh.add("Karchham");
				damsOfHimachalPradesh.add("Kol");
				damsOfHimachalPradesh.add("Largi");
				damsOfHimachalPradesh.add("Malana");
				damsOfHimachalPradesh.add("Nathpa Jhakri");
				damsOfHimachalPradesh.add("Pandoh");
				damsOfHimachalPradesh.add("Parbati");
				damsOfHimachalPradesh.add("Pong");
				damsOfHimachalPradesh.add("Sawra- Kuddu");

				Collection<String> damsOfJharkhand = new ArrayList<String>();
				damsOfJharkhand.add("Amanat");
				damsOfJharkhand.add("Anjanwa");
				damsOfJharkhand.add("Anraj");
				damsOfJharkhand.add("Baksa");
				damsOfJharkhand.add("Bandha");
				damsOfJharkhand.add("kaushalya");
				damsOfJharkhand.add("Baranadi");
				damsOfJharkhand.add("Barhi");
				damsOfJharkhand.add("Basuki");
				damsOfJharkhand.add("Batane");
				damsOfJharkhand.add("Batre");
				damsOfJharkhand.add("Bhairwa");
				damsOfJharkhand.add("Bhavnikhand");
				damsOfJharkhand.add("Bhutanduba");
				damsOfJharkhand.add("Bucha Opa");
				damsOfJharkhand.add("Burhai");
				damsOfJharkhand.add("Chandil");
				damsOfJharkhand.add("Chatania Ghat");
				damsOfJharkhand.add("Chinda");
				damsOfJharkhand.add("Chirka");
				damsOfJharkhand.add("Danro");
				damsOfJharkhand.add("Dhankai");
				damsOfJharkhand.add("Dhansingtoli");
				damsOfJharkhand.add("Dhulki");
				damsOfJharkhand.add("Diggalpahari");
				damsOfJharkhand.add("Garhi");
				damsOfJharkhand.add("Getalsud");
				damsOfJharkhand.add("Ghaghra");
				damsOfJharkhand.add("Gonda");
				damsOfJharkhand.add("Hatia");
				damsOfJharkhand.add("Hiru");
				damsOfJharkhand.add("Icha");
				damsOfJharkhand.add("Jaipur");
				damsOfJharkhand.add("Jamunia");
				damsOfJharkhand.add("Jenasai");
				damsOfJharkhand.add("Jharjhara");
				damsOfJharkhand.add("Kanhar");
				damsOfJharkhand.add("Kans");
				damsOfJharkhand.add("Kansjore");
				damsOfJharkhand.add("Karawani");
				damsOfJharkhand.add("Katri");
				damsOfJharkhand.add("Kesho");
				damsOfJharkhand.add("Khudia");
				damsOfJharkhand.add("Konar");
				damsOfJharkhand.add("Larwa");
				damsOfJharkhand.add("Latratu");
				damsOfJharkhand.add("Left Banki");
				damsOfJharkhand.add("Lorgara");
				damsOfJharkhand.add("Lotia");
				damsOfJharkhand.add("Maithon");
				damsOfJharkhand.add("Malay");
				damsOfJharkhand.add("Masanjor");
				damsOfJharkhand.add("Masaria");
				damsOfJharkhand.add("Murahir");
				damsOfJharkhand.add("Nakti");
				damsOfJharkhand.add("Nalkari");
				damsOfJharkhand.add("Nandini");
				damsOfJharkhand.add("North Koel");
				damsOfJharkhand.add("Palna");
				damsOfJharkhand.add("Panchat");
				damsOfJharkhand.add("Panchkhero");
				damsOfJharkhand.add("Pandarwa");
				damsOfJharkhand.add("Paras");
				damsOfJharkhand.add("Punasi");
				damsOfJharkhand.add("Raisa");
				damsOfJharkhand.add("Ramrekha");
				damsOfJharkhand.add("Salaiya");
				damsOfJharkhand.add("Satpotka");
				damsOfJharkhand.add("Sitaram");
				damsOfJharkhand.add("Sonua");
				damsOfJharkhand.add("Sudhari Nala");
				damsOfJharkhand.add("Sugathan");
				damsOfJharkhand.add("Sukri");
				damsOfJharkhand.add("Sunder");
				damsOfJharkhand.add("Surangi");
				damsOfJharkhand.add("Suryodi");
				damsOfJharkhand.add("Tahlay");
				damsOfJharkhand.add("Tajna");
				damsOfJharkhand.add("Tapkara");
				damsOfJharkhand.add("Temrain");
				damsOfJharkhand.add("Tenughat");
				damsOfJharkhand.add("Tilaiya");
				damsOfJharkhand.add("Torai");
				damsOfJharkhand.add("Torlow");
				damsOfJharkhand.add("Upper Shankh");

				Collection<String> damsOfKerala = new ArrayList<String>();
				damsOfKerala.add("Anathode Flanking (Eb)");
				damsOfKerala.add("Anayirangal");
				damsOfKerala.add("Aruvikkara");
				damsOfKerala.add("Azhutha");
				damsOfKerala.add("Cavaiar");
				damsOfKerala.add("Cheruthoni");
				damsOfKerala.add("Chimoni");
				damsOfKerala.add("Chulliar (Gayathri Stage-II) (Id)");
				damsOfKerala.add("Erattayar");
				damsOfKerala.add("Idamalayar");
				damsOfKerala.add("Idukki");
				damsOfKerala.add("Kakkayam");
				damsOfKerala.add("Kakki");
				damsOfKerala.add("Kallada");
				damsOfKerala.add("Kallar");
				damsOfKerala.add("Kallarkutty");
				damsOfKerala.add("Kanhira");
				damsOfKerala.add("Karapuzha");
				damsOfKerala.add("Kosani Saddle");
				damsOfKerala.add("Kottagiri Saddle");
				damsOfKerala.add("Kulamavu");
				damsOfKerala.add("Kullar (Sabarigiri Aug.)");
				damsOfKerala.add("Kundala");
				damsOfKerala.add("Kutiyar Diversion");
				damsOfKerala.add("Kuttiyadi");
				damsOfKerala.add("Kuttiyadi Aug. Saddle");
				damsOfKerala.add("Kuttiyadi Spillway");
				damsOfKerala.add("Lower Periyar");
				damsOfKerala.add("Madupetty");
				damsOfKerala.add("Malampuzha");
				damsOfKerala.add("Malankara");
				damsOfKerala.add("Mangalam");
				damsOfKerala.add("Meenar");
				damsOfKerala.add("Meenkara");
				damsOfKerala.add("Narakakanam Diversion");
				damsOfKerala.add("Near Kottagiri Saddle");
				damsOfKerala.add("Neyyar");
				damsOfKerala.add("Pamba");
				damsOfKerala.add("Parambikulam");
				damsOfKerala.add("Peechi");
				damsOfKerala.add("Peppara");
				damsOfKerala.add("Periyar");
				damsOfKerala.add("Peruvaripallam");
				damsOfKerala.add("Ponmudi");
				damsOfKerala.add("Poomala");
				damsOfKerala.add("Poringalkuthu");
				damsOfKerala.add("Pothundy");
				damsOfKerala.add("Sengulam");
				damsOfKerala.add("Sholayar");
				damsOfKerala.add("Sholayar Flanking");
				damsOfKerala.add("Siruvani");
				damsOfKerala.add("Tunacadavu");
				damsOfKerala.add("Upper Moozhiyar");
				damsOfKerala.add("Upper Moozhiyar Spillway");
				damsOfKerala.add("Vazhany");
				damsOfKerala.add("Vazhikkadavu");
				damsOfKerala.add("Veluthoda Forebay");
				damsOfKerala.add("Walayar");

				Collection<String> damsOfGujarat = new ArrayList<String>();
				damsOfGujarat.add("Aamli Chharchhoda");
				damsOfGujarat.add("Abhalwad");
				damsOfGujarat.add("Adhia");
				damsOfGujarat.add("Adhochhani");
				damsOfGujarat.add("Adhoi- I");
				damsOfGujarat.add("Adpur");
				damsOfGujarat.add("Advana");
				damsOfGujarat.add("Aji I");
				damsOfGujarat.add("Aji II");
				damsOfGujarat.add("Aji III");
				damsOfGujarat.add("Ajwa");
				damsOfGujarat.add("Alan Sagar");
				damsOfGujarat.add("Amalwant");
				damsOfGujarat.add("Ambajal");
				damsOfGujarat.add("Ambakui");
				damsOfGujarat.add("Ambala");
				damsOfGujarat.add("Ambani Khodiar");
				damsOfGujarat.add("Ambaradi");
				damsOfGujarat.add("Amirpur");
				damsOfGujarat.add("Anandapar");
				damsOfGujarat.add("Andhariparpata");
				damsOfGujarat.add("Angianawa");
				damsOfGujarat.add("Anida");
				damsOfGujarat.add("Arrni");
				damsOfGujarat.add("Badargadh");
				damsOfGujarat.add("Badi-Padva");
				damsOfGujarat.add("Bagad");
				damsOfGujarat.add("Baladhor");
				damsOfGujarat.add("Balamdi");
				damsOfGujarat.add("Balapar Budadro");
				damsOfGujarat.add("Baldeva");
				damsOfGujarat.add("Baliyawad");
				damsOfGujarat.add("Bamanbore");
				damsOfGujarat.add("Bambhanka");
				damsOfGujarat.add("Bandhara");
				damsOfGujarat.add("Bandi");
				damsOfGujarat.add("Bangawadi");
				damsOfGujarat.add("Baranda");
				damsOfGujarat.add("Baukha");
				damsOfGujarat.add("Bedi");
				damsOfGujarat.add("Bela");
				damsOfGujarat.add("Berachiya");
				damsOfGujarat.add("Bhadar");
				damsOfGujarat.add("Bhadreshwar");
				damsOfGujarat.add("Bhaguda");
				damsOfGujarat.add("Bhandaria");
				damsOfGujarat.add("Bhanmer");
				damsOfGujarat.add("Bharad");
				damsOfGujarat.add("Bharapar");
				damsOfGujarat.add("Bharudia");
				damsOfGujarat.add("Bhimdad");
				damsOfGujarat.add("Bhuj");
				damsOfGujarat.add("Bhuki");
				damsOfGujarat.add("Bodi");
				damsOfGujarat.add("Borsi");
				damsOfGujarat.add("Brahmani");
				damsOfGujarat.add("Burkhan");
				damsOfGujarat.add("Butta");
				damsOfGujarat.add("Chachka");
				damsOfGujarat.add("Chandrabhaga");
				damsOfGujarat.add("Chang");
				damsOfGujarat.add("Chavadka");
				damsOfGujarat.add("Chhaparvadi");
				damsOfGujarat.add("Chimnabai-Lake");
				damsOfGujarat.add("Chonda");
				damsOfGujarat.add("Chopadavav");
				damsOfGujarat.add("Chorwadala");
				damsOfGujarat.add("Dabahada");
				damsOfGujarat.add("Dabasang");
				damsOfGujarat.add("Dadar");
				damsOfGujarat.add("Daiminisar");
				damsOfGujarat.add("Dodfavanta");
				damsOfGujarat.add("Domda M.I");
				damsOfGujarat.add("Facharia");
				damsOfGujarat.add("Faddanbeti");
				damsOfGujarat.add("Fakirwadi");
				damsOfGujarat.add("Falku");
				damsOfGujarat.add("Faradi");
				damsOfGujarat.add("Farera");
				damsOfGujarat.add("Fatehgadh");
				damsOfGujarat.add("Fodaraness");
				damsOfGujarat.add("Fulzar");
				damsOfGujarat.add("Gadhada- Rasaji");
				damsOfGujarat.add("Gadhki");
				damsOfGujarat.add("Gajansagar");
				damsOfGujarat.add("Gajod");
				damsOfGujarat.add("Gaurishankar");
				damsOfGujarat.add("Gautameshwar");
				damsOfGujarat.add("Gebanshapir");
				damsOfGujarat.add("Ghee");
				damsOfGujarat.add("Ghela Somnath");
				damsOfGujarat.add("Ghodadharoi");
				damsOfGujarat.add("Godechi");
				damsOfGujarat.add("Godhatad");
				damsOfGujarat.add("Gokhalana");
				damsOfGujarat.add("Goma");
				damsOfGujarat.add("Gondali");
				damsOfGujarat.add("Goyala");
				damsOfGujarat.add("Goyasundal");
				damsOfGujarat.add("Gugariyana");
				damsOfGujarat.add("Guhai");
				damsOfGujarat.add("Guneli");
				damsOfGujarat.add("Hadaf");
				damsOfGujarat.add("Halara");
				damsOfGujarat.add("Hamapur");
				damsOfGujarat.add("Hamipara");
				damsOfGujarat.add("Hanol");
				damsOfGujarat.add("Hansthal");
				damsOfGujarat.add("Harwant");
				damsOfGujarat.add("Hatadi");
				damsOfGujarat.add("Hathasani");
				damsOfGujarat.add("Hathidra");
				damsOfGujarat.add("Hathmati");
				damsOfGujarat.add("Ingorala");
				damsOfGujarat.add("Isar");
				damsOfGujarat.add("Ishwariya");
				damsOfGujarat.add("Jadawas");
				damsOfGujarat.add("Jaday");

				Collection<String> damsOfMadhyaPradesh = new ArrayList<String>();
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");
				damsOfMadhyaPradesh.add("Amanat");

				Collection<String> damsOfMaharashtra = new ArrayList<String>();
				damsOfMaharashtra.add("Dhamapur");
				damsOfMaharashtra.add("Vihar");
				damsOfMaharashtra.add("Ekrukh");
				damsOfMaharashtra.add("Shirsufal");
				damsOfMaharashtra.add("Tulshi");
				damsOfMaharashtra.add("Khadakwasla");
				damsOfMaharashtra.add("Ashti");
				damsOfMaharashtra.add("Mhaswad");
				damsOfMaharashtra.add("Tansa");
				damsOfMaharashtra.add("Shetfal");
				damsOfMaharashtra.add("Khairbandha");
				damsOfMaharashtra.add("Pathari");
				damsOfMaharashtra.add("Chankapur");
				damsOfMaharashtra.add("Ramtek");
				damsOfMaharashtra.add("Chandpur");
				damsOfMaharashtra.add("Walwan");
				damsOfMaharashtra.add("Darna");
				damsOfMaharashtra.add("Bodalkasa");
				damsOfMaharashtra.add("Asolamendha");
				damsOfMaharashtra.add("Shirvata");
				damsOfMaharashtra.add("Thokarwadi");
				damsOfMaharashtra.add("Chorkhamara");
				damsOfMaharashtra.add("Ghorazari");
				damsOfMaharashtra.add("Bhandardara");
				damsOfMaharashtra.add("Bhatghar");
				damsOfMaharashtra.add("Mulshi");
				damsOfMaharashtra.add("Ghanewadi");
				damsOfMaharashtra.add("Visapur");

		
		Collection<String> damsOfManipur=new ArrayList<String>();
		
		damsOfManipur.add("Khoupum");
		damsOfManipur.add("Khuga");
		damsOfManipur.add("Singda");
		damsOfManipur.add("Thoubal");
		
		Collection<String> damsOfMeghalaya=new ArrayList<String>();
		
		damsOfMeghalaya.add("Khandong");
		damsOfMeghalaya.add("Kyrdemkulai");
		damsOfMeghalaya.add("Mawphlang");
		damsOfMeghalaya.add("Myntdu-Leshka");
		damsOfMeghalaya.add("Nongkhyllem");
		damsOfMeghalaya.add("Umiam");
		damsOfMeghalaya.add("Umtru");
		
		Collection<String> damsOfMizoram=new ArrayList<String>();
		
		damsOfMizoram.add("Serlui B");
		damsOfMizoram.add("Tuirial");
		
		Collection<String> damsOfNagaland=new ArrayList<String>();
		
		damsOfNagaland.add("Doyang Hep");
		
		Collection<String> damsOfOdisha=new ArrayList<String>();
		
		damsOfOdisha.add("Alubani");
		damsOfOdisha.add("Aradei");
		damsOfOdisha.add("Arikul");
		damsOfOdisha.add("Badabandha");
		damsOfOdisha.add("Badanalla");
		damsOfOdisha.add("Badjore");
		damsOfOdisha.add("Baghalati");
		damsOfOdisha.add("Baghjharan");
		damsOfOdisha.add("Baghua (MI)");
		damsOfOdisha.add("Baghua");
		damsOfOdisha.add("Balaskumpa");
		damsOfOdisha.add("Balimela");
		damsOfOdisha.add("Bankabal");
		damsOfOdisha.add("Banksal");
		damsOfOdisha.add("Baura");
		damsOfOdisha.add("Bautia");
		damsOfOdisha.add("Bedapada");
		damsOfOdisha.add("Behera");
		damsOfOdisha.add("Benikpur");
		damsOfOdisha.add("Bhagirijhala");
		damsOfOdisha.add("Bhallugahi");
		damsOfOdisha.add("Bhaluguda");
		damsOfOdisha.add("Bhanjanagar");
		damsOfOdisha.add("Bhaskel");
		damsOfOdisha.add("Bhatrajore");
		damsOfOdisha.add("Bhetabar");
		damsOfOdisha.add("Bhitiri Bediguda");
		damsOfOdisha.add("Budhabudiani");
		damsOfOdisha.add("Chhamundia");
		damsOfOdisha.add("Chhatenjore");
		damsOfOdisha.add("Chheligada");
		damsOfOdisha.add("Dadara Ghati");
		damsOfOdisha.add("Daha(OD)");
		damsOfOdisha.add("Damsal");
		damsOfOdisha.add("Dasamanthapur");
		damsOfOdisha.add("Debijharan");
		damsOfOdisha.add("Deo(OD)");
		damsOfOdisha.add("Deojharan");
		damsOfOdisha.add("Deras");
		damsOfOdisha.add("Derjang");
		damsOfOdisha.add("Dhanei");
		damsOfOdisha.add("Dhulipaunsia");
		damsOfOdisha.add("Domkutch");
		damsOfOdisha.add("Dumerbahal");
		damsOfOdisha.add("Gaikhai(Minor)");
		damsOfOdisha.add("Ganianalla");
		damsOfOdisha.add("Garh");
		damsOfOdisha.add("Gayapathar");
		damsOfOdisha.add("Ghagara");
		damsOfOdisha.add("Ghatakeswar");
		damsOfOdisha.add("Ghodahada");
		damsOfOdisha.add("Gohira");
		damsOfOdisha.add("Goibali");
		damsOfOdisha.add("Gundurapasi");
		damsOfOdisha.add("Gurlijore");
		damsOfOdisha.add("HATIANALLA M.I.P");
		damsOfOdisha.add("Hadua");
		damsOfOdisha.add("Haguri");
		damsOfOdisha.add("Haladia");
		damsOfOdisha.add("Hanumantia");
		damsOfOdisha.add("Harabhangi");
		damsOfOdisha.add("Hariharjore");
		damsOfOdisha.add("Haripur");
		damsOfOdisha.add("Hirakud");
		damsOfOdisha.add("Indrawati");
		damsOfOdisha.add("Jagadala");
		damsOfOdisha.add("Jaigarh");
		damsOfOdisha.add("Jalaput");
		damsOfOdisha.add("Jambhira");
		damsOfOdisha.add("Jamboonala");
		damsOfOdisha.add("Jamuna Bundha");
		damsOfOdisha.add("Jaunria");
		damsOfOdisha.add("Jharanai");
		damsOfOdisha.add("Jharbandha");
		damsOfOdisha.add("Jhumuka");
		damsOfOdisha.add("Jodabadia");
		damsOfOdisha.add("Kakudajodi");
		damsOfOdisha.add("Kalakala");
		damsOfOdisha.add("Kalijodi");
		damsOfOdisha.add("Kalo");
		damsOfOdisha.add("Kangani");
		damsOfOdisha.add("Kanheinalla");
		damsOfOdisha.add("Kanjhari");
		damsOfOdisha.add("Kansabansa");
		damsOfOdisha.add("Kansbahal");
		damsOfOdisha.add("Kanteijhara");
		damsOfOdisha.add("Kantesir");
		damsOfOdisha.add("Kanupur");
		damsOfOdisha.add("Kapur");
		damsOfOdisha.add("Karada");
		damsOfOdisha.add("Karanjkote");
		damsOfOdisha.add("Khadakhai");
		damsOfOdisha.add("Khajuria");
		damsOfOdisha.add("Khandijharan");
		damsOfOdisha.add("Khasbahal");
		damsOfOdisha.add("Khuntapada");
		damsOfOdisha.add("Kiajhar");
		damsOfOdisha.add("Kodabhal");
		damsOfOdisha.add("Kodigam");
		damsOfOdisha.add("Konheimunda");
		damsOfOdisha.add("Koska");
		damsOfOdisha.add("Kuanria");
		damsOfOdisha.add("Kukurpeta");
		damsOfOdisha.add("Kumbho");
		damsOfOdisha.add("Kureijodi");
		damsOfOdisha.add("Kusunpur");
		damsOfOdisha.add("Laigam");
		damsOfOdisha.add("Lakhaparbat");
		damsOfOdisha.add("Laupal");
		damsOfOdisha.add("Laxmipur");
		damsOfOdisha.add("Liar");
		damsOfOdisha.add("Lower Indra");
		damsOfOdisha.add("Lower Suktal");
		damsOfOdisha.add("Magara");
		damsOfOdisha.add("Maharanisagar");
		damsOfOdisha.add("Mahendratanaya");
		damsOfOdisha.add("Mahisanalla");
		damsOfOdisha.add("Malakangiri");
		damsOfOdisha.add("Mandira");
		damsOfOdisha.add("Manjhor");
		damsOfOdisha.add("Marudi");
		damsOfOdisha.add("Masina");
		damsOfOdisha.add("Mathan Pal");
		damsOfOdisha.add("Mathili");
		damsOfOdisha.add("Muran");
		damsOfOdisha.add("Nesa");
		damsOfOdisha.add("Nimajhar Mip");
		damsOfOdisha.add("Padampur");
		damsOfOdisha.add("Paitagam");
		damsOfOdisha.add("Panaskhal");
		damsOfOdisha.add("Pani-Pailla");
		damsOfOdisha.add("Pansapal");
		damsOfOdisha.add("Parhal");
		damsOfOdisha.add("Paunsia");
		damsOfOdisha.add("Pilasalki");
		damsOfOdisha.add("Pipal");
		damsOfOdisha.add("Pitamahal");
		damsOfOdisha.add("Podagada");
		damsOfOdisha.add("Pokharia");
		damsOfOdisha.add("Pratappur");
		damsOfOdisha.add("Pujiladu");
		damsOfOdisha.add("Raghubeda");
		damsOfOdisha.add("Raghunath Sagar");
		damsOfOdisha.add("Raijharan");
		damsOfOdisha.add("Ramaguda");
		damsOfOdisha.add("Ramiala");
		damsOfOdisha.add("Randa");
		damsOfOdisha.add("Remal");
		damsOfOdisha.add("Rengali");
		damsOfOdisha.add("Ret");
		damsOfOdisha.add("Rissia");
		damsOfOdisha.add("Rukura");
		damsOfOdisha.add("Rungaon");
		damsOfOdisha.add("Saipala");
		damsOfOdisha.add("Salandi");
		damsOfOdisha.add("Salia");
		damsOfOdisha.add("Sanasialinai");
		damsOfOdisha.add("Sanmachhakandana ");
		damsOfOdisha.add("Sapua (Medium)");
		damsOfOdisha.add("Sarapa");
		damsOfOdisha.add("Saraphgarh");
		damsOfOdisha.add("Satiguda");
		damsOfOdisha.add("Sendhie");
		damsOfOdisha.add("Soroda");
		damsOfOdisha.add("Suhagi");
		damsOfOdisha.add("Sunaghai");
		damsOfOdisha.add("Sunamuhin");
		damsOfOdisha.add("Sundar(OD)");
		damsOfOdisha.add("Sunei");
		damsOfOdisha.add("Talasara");
		damsOfOdisha.add("Talkhol");
		damsOfOdisha.add("Tangarakana");
		damsOfOdisha.add("Telengiri(T.M.I.P)");
		damsOfOdisha.add("Tenar");
		damsOfOdisha.add("Tikarpada");
		damsOfOdisha.add("Tilipada");
		damsOfOdisha.add("Titilagarh(Stage- II)");
		damsOfOdisha.add("Upper Jonk");
		damsOfOdisha.add("Upper Kolab	");
		damsOfOdisha.add("Upper Lanth");
		damsOfOdisha.add("Upper Suktel");
		
		Collection<String> damsOfPunjab=new ArrayList<String>();
		
		damsOfPunjab.add("Chohal");
		damsOfPunjab.add("Damsal");
		damsOfPunjab.add("Dholbaha");
		damsOfPunjab.add("Jainti");
		damsOfPunjab.add("Janauri");
		damsOfPunjab.add("Maili");
		damsOfPunjab.add("Mirzapur");
		damsOfPunjab.add("Patiari");
		damsOfPunjab.add("Perch");
		damsOfPunjab.add("Ranjit Sagar");
		damsOfPunjab.add("Saleran");
		damsOfPunjab.add("Shahpur Kandi");
		damsOfPunjab.add("Siswan");
		damsOfPunjab.add("Thana");
		
		Collection<String> damsOfRajasthan=new ArrayList<String>();
		
		damsOfRajasthan.add("Abhaypura");
		damsOfRajasthan.add("Aklera Sagar");
		damsOfRajasthan.add("Alnia");
		damsOfRajasthan.add("Amli Kheda");
		damsOfRajasthan.add("Angore");
		damsOfRajasthan.add("Anwasa");
		damsOfRajasthan.add("Arwar");
		damsOfRajasthan.add("Atawara");
		damsOfRajasthan.add("Babara");
		damsOfRajasthan.add("Badgaon");
		damsOfRajasthan.add("Bagolia");
		damsOfRajasthan.add("Bajrang");
		damsOfRajasthan.add("Banakiya");
		damsOfRajasthan.add("Bandi");
		damsOfRajasthan.add("Bankali");
		damsOfRajasthan.add("Baradpura");
		damsOfRajasthan.add("Baretha Bund");
		damsOfRajasthan.add("Bari Mansarowar");
		damsOfRajasthan.add("Barkheri");
		damsOfRajasthan.add("Bassi");
		damsOfRajasthan.add("Basundni");
		damsOfRajasthan.add("Bethali");
		damsOfRajasthan.add("Bhagora");
		damsOfRajasthan.add("Bhagwatgardh");
		damsOfRajasthan.add("Bhamri Tandi");
		damsOfRajasthan.add("Bhanwar Semla");
		damsOfRajasthan.add("Bhatia");
		damsOfRajasthan.add("Bhimlat");
		damsOfRajasthan.add("Bhimsagar");
		damsOfRajasthan.add("Bhopal Sagar ");
		damsOfRajasthan.add("Bhula");
		damsOfRajasthan.add("Bilas");
		damsOfRajasthan.add("Bisalpur");
		damsOfRajasthan.add("Bithan");
		damsOfRajasthan.add("Biya Pada");
		damsOfRajasthan.add("Borda");
		damsOfRajasthan.add("Boria");
		damsOfRajasthan.add("Buchara");
		damsOfRajasthan.add("Bundika Gothra");
		damsOfRajasthan.add("Burdha");
		damsOfRajasthan.add("Butri");
		damsOfRajasthan.add("Chacha Kheri");
		damsOfRajasthan.add("Chandelao");
		damsOfRajasthan.add("Chandrabhaga");
		damsOfRajasthan.add("Chandrana");
		damsOfRajasthan.add("Bheru");
		damsOfRajasthan.add("Chaparwara");
		damsOfRajasthan.add("Kunty");
		damsOfRajasthan.add("Chatra");
		damsOfRajasthan.add("Chauli");
		damsOfRajasthan.add("Chhapi");
		damsOfRajasthan.add("Chikalwar");
		damsOfRajasthan.add("Chittoli");
		damsOfRajasthan.add("Choti-Tandi");
		damsOfRajasthan.add("DANDIA");
		damsOfRajasthan.add("Daya");
		damsOfRajasthan.add("Deopura");
		damsOfRajasthan.add("Deoriya");
		damsOfRajasthan.add("Dheel");
		damsOfRajasthan.add("Dhanta");
		damsOfRajasthan.add("Dindoli");
		damsOfRajasthan.add("Domti Kokra");
		damsOfRajasthan.add("Dorai");
		damsOfRajasthan.add("Dudka");
		damsOfRajasthan.add("Dugari");
		damsOfRajasthan.add("Dunglawani");
		damsOfRajasthan.add("Fateh Sagar");
		damsOfRajasthan.add("Gadola");
		damsOfRajasthan.add("Gagrin");
		damsOfRajasthan.add("Galai Sagar");
		damsOfRajasthan.add("Galwa");
		damsOfRajasthan.add("Galwania");
		damsOfRajasthan.add("Gambhiri");
		damsOfRajasthan.add("Gararda");
		damsOfRajasthan.add("Girinanda");
		damsOfRajasthan.add("Giroliya");
		damsOfRajasthan.add("Girwar");
		damsOfRajasthan.add("Godana");
		damsOfRajasthan.add("Gopalpura");
		damsOfRajasthan.add("Gosunda");
		damsOfRajasthan.add("Govta");
		damsOfRajasthan.add("Goyaka");
		damsOfRajasthan.add("Gudha");
		damsOfRajasthan.add("Gulandi");
		damsOfRajasthan.add("Hamja Kheri");
		damsOfRajasthan.add("Harish Chandra sagar");
		damsOfRajasthan.add("Harro");
		damsOfRajasthan.add("Harsora");
		damsOfRajasthan.add("Hemavas Saddle");
		damsOfRajasthan.add("Hemawas");
		damsOfRajasthan.add("Himmatgarhi");
		damsOfRajasthan.add("Hindlot");
		damsOfRajasthan.add("Hingonia");
		damsOfRajasthan.add("Jagpura");
		damsOfRajasthan.add("Jai Samand");
		damsOfRajasthan.add("Jaisamand");
		damsOfRajasthan.add("Jakham");
		damsOfRajasthan.add("Jaswant");
		damsOfRajasthan.add("Jawai");
		damsOfRajasthan.add("Jawahar Sagar");
		
		
		Collection<String> damsOfSikkim=new ArrayList<String>();
		
		damsOfSikkim.add("Rangit III");
		damsOfSikkim.add("Rangpo");
		damsOfSikkim.add("Rongli");
		damsOfSikkim.add("Teesta -V");
		damsOfSikkim.add("Teesta-III");
		damsOfSikkim.add("Teesta-IV");

		Collection<String> damsOfTamilNadu=new ArrayList<String>();

		damsOfTamilNadu.add("Aanaimaduvu");
		damsOfTamilNadu.add("Adavinainarkovil");
		damsOfTamilNadu.add("Aliyar");
		damsOfTamilNadu.add("Amaravathi");
		damsOfTamilNadu.add("Anaikuttam");
		damsOfTamilNadu.add("Andiappanur");
		damsOfTamilNadu.add("Avalanche");
		damsOfTamilNadu.add("Barur");
		damsOfTamilNadu.add("Berijam");
		damsOfTamilNadu.add("Bungihalla Bund");
		damsOfTamilNadu.add("Chembarambakkam");
		damsOfTamilNadu.add("Chinnar");
		damsOfTamilNadu.add("Chittar");
		damsOfTamilNadu.add("Chittar II");
		damsOfTamilNadu.add("East Varahapallam");
		damsOfTamilNadu.add("Emerald");
		damsOfTamilNadu.add("Eravangalar");
		damsOfTamilNadu.add("Gatana");
		damsOfTamilNadu.add("Glenmorgan");
		damsOfTamilNadu.add("Glenmorgan Forbay");
		damsOfTamilNadu.add("Golwarpatti");
		damsOfTamilNadu.add("Gomukhinadi");
		damsOfTamilNadu.add("Gundar");
		damsOfTamilNadu.add("Gunderipallam");
		damsOfTamilNadu.add("Highwavys");
		damsOfTamilNadu.add("Irukkangudi");
		damsOfTamilNadu.add("Kadamparai");
		damsOfTamilNadu.add("	Kamraju Sagar");
		damsOfTamilNadu.add("Kariakoil");
		damsOfTamilNadu.add("Karuppanadhi");
		damsOfTamilNadu.add("Kelavarapalli");
		damsOfTamilNadu.add("Kesarigulihalla");
		damsOfTamilNadu.add("Kodaganar");
		damsOfTamilNadu.add("Kodumudiyar");
		damsOfTamilNadu.add("Krishnagiri");
		damsOfTamilNadu.add("Kullursandai");
		damsOfTamilNadu.add("Kundah Palam");
		damsOfTamilNadu.add("Kuppanatham");
		damsOfTamilNadu.add("Kuthiraiyar");
		damsOfTamilNadu.add("Kuttiyadi");
		damsOfTamilNadu.add("Kuttiyar");
		damsOfTamilNadu.add("Lower Bhavani");
		damsOfTamilNadu.add("	Lower Kodayar");
		damsOfTamilNadu.add("Lower Nirar");
		damsOfTamilNadu.add("Mambazhathuraiyar");
		damsOfTamilNadu.add("Manalar");
		damsOfTamilNadu.add("Manimukthanadhi");
		damsOfTamilNadu.add("Manimuthar");
		damsOfTamilNadu.add("Manjalar");
		damsOfTamilNadu.add("Maravakandi Forbay");
		damsOfTamilNadu.add("Marudhanadi");
		damsOfTamilNadu.add("Mettur");
		damsOfTamilNadu.add("Mirugandanadhi");
		damsOfTamilNadu.add("Mordhana");
		damsOfTamilNadu.add("Moyar Forebay");
		damsOfTamilNadu.add("Mukurthy");
		damsOfTamilNadu.add("Nagavathi");
		damsOfTamilNadu.add("Nallathangal Odai");
		damsOfTamilNadu.add("Nambiar");
		damsOfTamilNadu.add("Nanganjiyar");
		damsOfTamilNadu.add("Nilayur Bed");
		damsOfTamilNadu.add("Noyyal Athupalayam");
		damsOfTamilNadu.add("Noyyal Orathupalayam");
		damsOfTamilNadu.add("Palar Porundalar");
		damsOfTamilNadu.add("Pambar");
		damsOfTamilNadu.add("Papanasam");
		damsOfTamilNadu.add("Parappalar");
		damsOfTamilNadu.add("ParsonS Valley");
		damsOfTamilNadu.add("Pechiparai");
		damsOfTamilNadu.add("Pegumbahallah Forebay");
		damsOfTamilNadu.add("Periyar Forebay");
		damsOfTamilNadu.add("Perumpallam");
		damsOfTamilNadu.add("Perunchani");
		damsOfTamilNadu.add("Pilavukkal Kovilar");
		damsOfTamilNadu.add("Pilavukkal Periyar");
		damsOfTamilNadu.add("Pillur");
		damsOfTamilNadu.add("Poigaiyar");
		damsOfTamilNadu.add("Ponnaniar");
		damsOfTamilNadu.add("Poondi");
		damsOfTamilNadu.add("Porthimund");
		damsOfTamilNadu.add("Puthen");
		damsOfTamilNadu.add("Pykara");
		damsOfTamilNadu.add("Rajathope Kanar");
		damsOfTamilNadu.add("Ramanadhi");
		damsOfTamilNadu.add("Sathanur");
		damsOfTamilNadu.add("Sathiyar");
		damsOfTamilNadu.add("Servalar");
		damsOfTamilNadu.add("Shanmuganadhi");
		damsOfTamilNadu.add("Shenbagathope");
		damsOfTamilNadu.add("Sholayar");
		damsOfTamilNadu.add("Shoolagiri Chinnar");
		damsOfTamilNadu.add("Siddhamalli");
		damsOfTamilNadu.add("Sothupparai");
		damsOfTamilNadu.add("Thirumurthi");
		damsOfTamilNadu.add("Thoppaiyar");
		damsOfTamilNadu.add("Thumblahalli");
		damsOfTamilNadu.add("Uppar( Erode)");
		damsOfTamilNadu.add("Upper Aliyar");
		damsOfTamilNadu.add("Upper Bhavani");
		damsOfTamilNadu.add("Upper Kodayar");
		damsOfTamilNadu.add("Upper Kodayar Diversion");
		damsOfTamilNadu.add("Vadakku Paichaiyar");
		damsOfTamilNadu.add("Vaigai");
		damsOfTamilNadu.add("Vaniar");
		damsOfTamilNadu.add("Varadhamanadhi");
		damsOfTamilNadu.add("Varattar");
		damsOfTamilNadu.add("Varattupallam");
		damsOfTamilNadu.add("Vattamalaikarai Odai");
		damsOfTamilNadu.add("Vembakottai");
		damsOfTamilNadu.add("Vennir-Ar");
		damsOfTamilNadu.add("Vidur");
		damsOfTamilNadu.add("West Varahapallam Weir");
		damsOfTamilNadu.add("Western Catchment No. I");
		damsOfTamilNadu.add("Western Catchment No. II");
		damsOfTamilNadu.add("Western Catchment No. III");
		damsOfTamilNadu.add("Willington");
		
		Collection<String> damsOfTelangana =new ArrayList<String>();
		
		damsOfTelangana.add("Ada Village - Peddavagu");
		damsOfTelangana.add("Akkampalli");
		damsOfTelangana.add("Bandlavagu");
		damsOfTelangana.add("Bazarthathnur");
		damsOfTelangana.add("Bethampudi");
		damsOfTelangana.add("Bheemanpally");
		damsOfTelangana.add("Boath");
		damsOfTelangana.add("Boggulavagu");
		damsOfTelangana.add("Budhpur");
		damsOfTelangana.add("Chelamelavagu");
		damsOfTelangana.add("Choutaplly Hanuman Reddy Lift");
		damsOfTelangana.add("Dantakani Cheruvu");
		damsOfTelangana.add("Devathlacheru");
		damsOfTelangana.add("Dharamsagar");
		damsOfTelangana.add("Dindi");
		damsOfTelangana.add("Fox Sagar");
		damsOfTelangana.add("Gandipally");
		damsOfTelangana.add("Ghanpur Lake");
		damsOfTelangana.add("Gidda Cheru, Yellareddypet");
		damsOfTelangana.add("Gopaldinne");
		damsOfTelangana.add("Gudipalligattu");
		damsOfTelangana.add("Gujjulavagu , Gandhari");
		damsOfTelangana.add("	Gundetivagu Cheroo, Reddygudem");
		damsOfTelangana.add("Gundlavagu");
		damsOfTelangana.add("Himayat Sagar");
		damsOfTelangana.add("Indirammasagar, Anajpur");
		damsOfTelangana.add("Jutpally Weir/Jutepally");
		damsOfTelangana.add("Kaddam");
		damsOfTelangana.add("Kajjerla Anicut");
		damsOfTelangana.add("Kakarvani");
		damsOfTelangana.add("Kandlapalle Cheruvu");
		damsOfTelangana.add("Kesavari Samudram");
		damsOfTelangana.add("Kinnerasani");
		damsOfTelangana.add("Koil Sagar");
		damsOfTelangana.add("Komaram Bheem");
		damsOfTelangana.add("Komsettipally");
		damsOfTelangana.add("Kothacheru, Mamdabad");
		damsOfTelangana.add("Kotipally Vagu");
		damsOfTelangana.add("Koulasanala");
		damsOfTelangana.add("Krishnasamudram");
		damsOfTelangana.add("Kuppakanti");
		damsOfTelangana.add("Lakhnapur");
		damsOfTelangana.add("Lakhnavaram");
		damsOfTelangana.add("Lankasagar");
		damsOfTelangana.add("Adloor Yellareddy");
		damsOfTelangana.add("Bibipet");
		damsOfTelangana.add("Brahmanpally");
		damsOfTelangana.add("Large , Dharmaraopet");
		damsOfTelangana.add("Large , Garepally");
		damsOfTelangana.add("Garla");
		damsOfTelangana.add("Husnabad");
		damsOfTelangana.add("Ibrahimpatnam");
		damsOfTelangana.add("Indalwai");
		damsOfTelangana.add("Jangampally");
		damsOfTelangana.add("Kachapur");
		damsOfTelangana.add("Kamareddy");
		damsOfTelangana.add("Kapuram");
		damsOfTelangana.add("Khajar");
		damsOfTelangana.add("Manchippa");
		damsOfTelangana.add("Mustabad");
		damsOfTelangana.add("Ped allareddy");
		damsOfTelangana.add("Pulkal");
		damsOfTelangana.add("Raviryal");
		damsOfTelangana.add("Shameerpet");
		damsOfTelangana.add("Sultanabad");
		damsOfTelangana.add("Uppalwai");
		damsOfTelangana.add("Vilasagar");
		damsOfTelangana.add("Lower Manair");
		damsOfTelangana.add("Malikacheru");
		damsOfTelangana.add("Mallammacheruvu Saralnagar");
		damsOfTelangana.add("Malluruvagu");
		damsOfTelangana.add("Mathadivagu");
		damsOfTelangana.add("Hajipur");
		damsOfTelangana.add("Medi Cheru");
		damsOfTelangana.add("Melammacheru");
		damsOfTelangana.add("Mid Manair");
		damsOfTelangana.add("Modikuntavagu");
		damsOfTelangana.add("Mothe Cheruvu");
		damsOfTelangana.add("Mukkamamidi");
		damsOfTelangana.add("Mulavagu");
		damsOfTelangana.add("Munneru");
		damsOfTelangana.add("Musi");
		damsOfTelangana.add("Nagarjuna Sagar");
		damsOfTelangana.add("Nagarjunasagar Tail Pond");
		damsOfTelangana.add("Nallacheru");
		damsOfTelangana.add("Nallavagu");
		damsOfTelangana.add("Namaz Cheru");
		damsOfTelangana.add("Kasula");
		damsOfTelangana.add("Neelwai");
		damsOfTelangana.add("Bellempally");
		damsOfTelangana.add("Kothur");
		damsOfTelangana.add("Nizam Sagar");
		damsOfTelangana.add("Ookachettivagu");
		damsOfTelangana.add("Oora Cheru");
		damsOfTelangana.add("Osman Sagar");
		damsOfTelangana.add("Pakhal Lake");
		damsOfTelangana.add("Palair");
		damsOfTelangana.add("Palemvagu");
		damsOfTelangana.add("Pedda Cheru");
		damsOfTelangana.add("Challasamudram");
		damsOfTelangana.add("Chintapalli");
		damsOfTelangana.add("Inapur");
		damsOfTelangana.add("Indurthy");
		damsOfTelangana.add("Kodad");
		damsOfTelangana.add("Lingapur");
		damsOfTelangana.add("Potharam");
		damsOfTelangana.add("Shivanagudem");
		damsOfTelangana.add("Soan");
		damsOfTelangana.add("Stambampally");
		damsOfTelangana.add("Swamulavari Lingotam");
		damsOfTelangana.add("Thangadpally");
		damsOfTelangana.add("Vellutla");
		damsOfTelangana.add("Yellareddy");
		damsOfTelangana.add("Yelupugonda");
		damsOfTelangana.add("Lokaram");
		damsOfTelangana.add("Lokurthy");
		damsOfTelangana.add("Ragaboinagudem");
		damsOfTelangana.add("Lingal");
		damsOfTelangana.add("Peddavagu");
		damsOfTelangana.add("Peddavagu-Jagannathpur");
		damsOfTelangana.add("Perval");
		damsOfTelangana.add("Pocharam");
		damsOfTelangana.add("Polkicheru");
		damsOfTelangana.add("Posanipeta Cheruvu");
		damsOfTelangana.add("Jurala");
		damsOfTelangana.add("Narsapur");
		damsOfTelangana.add("Ramadugu");
		damsOfTelangana.add("Ramappa");
		damsOfTelangana.add("Rangasamudram");
		damsOfTelangana.add("Rasulacheru");
		damsOfTelangana.add("Salivagu");
		damsOfTelangana.add("Sangambanda");
		damsOfTelangana.add("Sankarasamudram");
		damsOfTelangana.add("Sarala Sagar");
		damsOfTelangana.add("Sarpanapally");
		damsOfTelangana.add("Sat Dodarna");
		damsOfTelangana.add("Sathanala");
		damsOfTelangana.add("Shanigram");
		damsOfTelangana.add("Singaraya");
		damsOfTelangana.add("Singasamudram");
		damsOfTelangana.add("Singhabhoopalem");
		damsOfTelangana.add("Singur");
		damsOfTelangana.add("Sirala");
		damsOfTelangana.add("Sriram Sagar");
		damsOfTelangana.add("Srisailam");
		damsOfTelangana.add("Srivari Samudram");
		damsOfTelangana.add("Stambala Cheru");
		damsOfTelangana.add("Suddavagu");
		damsOfTelangana.add("Suryanarayanacheru");
		damsOfTelangana.add("Swarna");
		damsOfTelangana.add("Taliperu");
		damsOfTelangana.add("Tatikunta");
		damsOfTelangana.add("Thalla Cheru");
		damsOfTelangana.add("Thotapally");
		damsOfTelangana.add("Upper Manair");
		damsOfTelangana.add("Utkoor Marepall");
		damsOfTelangana.add("Vattivagu");
		damsOfTelangana.add("Veerladevi Cheru");
		damsOfTelangana.add("Vemular");
		damsOfTelangana.add("Wyra");
		damsOfTelangana.add("Yellur");
		damsOfTelangana.add("Yenukunta");
		damsOfTelangana.add("Yerravagu");
		damsOfTelangana.add("Zildartippa");
		

		Collection<String> damsOfTripura=new ArrayList<String>();
		
		damsOfTripura.add("Gumti Hydro");
		
		Collection<String> damsOfuttarakhand=new ArrayList<String>();
		
		damsOfuttarakhand.add("Baigul");
		damsOfuttarakhand.add("Baur");
		damsOfuttarakhand.add("Bhimtal");
		damsOfuttarakhand.add("Dhauliganga");
		damsOfuttarakhand.add("Dhora");
		damsOfuttarakhand.add("Haripura");
		damsOfuttarakhand.add("Ichari");
		damsOfuttarakhand.add("Jamrani");
		damsOfuttarakhand.add("Koteshwar");
		damsOfuttarakhand.add("Lakhwar");
		damsOfuttarakhand.add("Maneri");
		damsOfuttarakhand.add("Nanak Sagar");
		damsOfuttarakhand.add("Ramganga");
		damsOfuttarakhand.add("Tehri");
		damsOfuttarakhand.add("Tumaria");

		Collection<String> damsOfUttarPradesh=new ArrayList<String>();
		System.out.println("===========================================u.p=====================================================");
		damsOfUttarPradesh.add("Adwa");
		damsOfUttarPradesh.add("Afzalgarh");
		damsOfUttarPradesh.add("Ahraura");
		damsOfUttarPradesh.add("Aunjhar");
		damsOfUttarPradesh.add("Bachara");
		damsOfUttarPradesh.add("Baghel Khand");
		damsOfUttarPradesh.add("Baghla");
		damsOfUttarPradesh.add("Balui Bandh");
		damsOfUttarPradesh.add("Balui");
		damsOfUttarPradesh.add("Banjari Kalan");
		damsOfUttarPradesh.add("Barwa");
		damsOfUttarPradesh.add("Barwa Sagar");
		damsOfUttarPradesh.add("Barwar");
		damsOfUttarPradesh.add("Barwatola");
		damsOfUttarPradesh.add("Bhagwan Pur");
		damsOfUttarPradesh.add("Bhainsora");
		damsOfUttarPradesh.add("Bhonka");
		damsOfUttarPradesh.add("Chandra Prabha");
		damsOfUttarPradesh.add("Chandrawal");
		damsOfUttarPradesh.add("Chittaurgarh");
		damsOfUttarPradesh.add("Deori");
		damsOfUttarPradesh.add("Dhandhraul");
		damsOfUttarPradesh.add("Dhenkwan");
		damsOfUttarPradesh.add("Dongia");
		damsOfUttarPradesh.add("Dongri");
		damsOfUttarPradesh.add("Ganeshpur");
		damsOfUttarPradesh.add("Garhwa");
		damsOfUttarPradesh.add("Ghooga");
		damsOfUttarPradesh.add("Ghori");
		damsOfUttarPradesh.add("Girgity");
		damsOfUttarPradesh.add("Gointha");
		damsOfUttarPradesh.add("Govind Sagar");
		damsOfUttarPradesh.add("Gularia");
		damsOfUttarPradesh.add("Gunta");
		damsOfUttarPradesh.add("Hinauti");
		damsOfUttarPradesh.add("Jaiwanti");
		damsOfUttarPradesh.add("Jamini");
		damsOfUttarPradesh.add("Jirgo");
		damsOfUttarPradesh.add("Jogendra");
		damsOfUttarPradesh.add("Kabrai");
		damsOfUttarPradesh.add("Kachnoda");
		damsOfUttarPradesh.add("Kargara");
		damsOfUttarPradesh.add("Keolari");
		damsOfUttarPradesh.add("Khairman");
		damsOfUttarPradesh.add("Khandeha");
		damsOfUttarPradesh.add("Khapatia");
		damsOfUttarPradesh.add("Khirihata");
		damsOfUttarPradesh.add("Kohar Gaddi");
		damsOfUttarPradesh.add("Kota");
		damsOfUttarPradesh.add("Kotra Khambha");
		damsOfUttarPradesh.add("Kuba Khurd");
		damsOfUttarPradesh.add("Lachura");
		damsOfUttarPradesh.add("Lower Khajuri");
		damsOfUttarPradesh.add("Majhgawan");
		damsOfUttarPradesh.add("Matatila");
		damsOfUttarPradesh.add("Maudaha");
		damsOfUttarPradesh.add("Meja");
		damsOfUttarPradesh.add("Moosakhand");
		damsOfUttarPradesh.add("Muirpur");
		damsOfUttarPradesh.add("Murtia");
		damsOfUttarPradesh.add("Nagwa");
		damsOfUttarPradesh.add("Nanauti");
		damsOfUttarPradesh.add("Narson");
		damsOfUttarPradesh.add("Naugarh");
		damsOfUttarPradesh.add("Newari");
		damsOfUttarPradesh.add("Obra");
		damsOfUttarPradesh.add("Ohen");
		damsOfUttarPradesh.add("Pachwara Lake");
		damsOfUttarPradesh.add("Pahari");
		damsOfUttarPradesh.add("Pahuj");
		damsOfUttarPradesh.add("Patharai");
		damsOfUttarPradesh.add("Pili");
		damsOfUttarPradesh.add("Ragura");
		damsOfUttarPradesh.add("Raipura");
		damsOfUttarPradesh.add("Rajghat");
		damsOfUttarPradesh.add("Rajkhar");
		damsOfUttarPradesh.add("Rampur");
		damsOfUttarPradesh.add("Rampur Kalyangarh");
		damsOfUttarPradesh.add("Rampur Pindaria");
		damsOfUttarPradesh.add("Rihand");
		damsOfUttarPradesh.add("Rohini");
		damsOfUttarPradesh.add("Sajnam");
		damsOfUttarPradesh.add("Saktesh Garh");
		damsOfUttarPradesh.add("Salarpur");
		damsOfUttarPradesh.add("Saprar");
		damsOfUttarPradesh.add("Sarai Garh");
		damsOfUttarPradesh.add("Sarda Sagar");
		damsOfUttarPradesh.add("Semri");
		damsOfUttarPradesh.add("Shahjad");
		damsOfUttarPradesh.add("Siori Lake");
		damsOfUttarPradesh.add("Sirsi");
		damsOfUttarPradesh.add("Sukhra");
		damsOfUttarPradesh.add("Suswar");
		damsOfUttarPradesh.add("Upper Khajuri");
		damsOfUttarPradesh.add("Urmil");
		damsOfUttarPradesh.add("Vijaipur");
		

		Collection<String> damsOfWestBengal=new ArrayList<String>();

		damsOfWestBengal.add("Bakreshwar");
		damsOfWestBengal.add("Bandhu");
		damsOfWestBengal.add("Bara Mandira");
		damsOfWestBengal.add("Barabhum");
		damsOfWestBengal.add("Beko");
		damsOfWestBengal.add("Dangrajhore");
		damsOfWestBengal.add("Dimu");
		damsOfWestBengal.add("Futiary");
		damsOfWestBengal.add("Golamarajore");
		damsOfWestBengal.add("Hanumata");
		damsOfWestBengal.add("Hinglow Irrigation Scheme");
		damsOfWestBengal.add("Kangsabati Kumari");
		damsOfWestBengal.add("Kanjan");
		damsOfWestBengal.add("Karrior");
		damsOfWestBengal.add("Khairabera");
		damsOfWestBengal.add("Kumari");
		damsOfWestBengal.add("Lipania");
		damsOfWestBengal.add("Lower : PPSP");
		damsOfWestBengal.add("Moutorejore");
		damsOfWestBengal.add("Muruguma");
		damsOfWestBengal.add("Nachan Irri. Scheme");
		damsOfWestBengal.add("Paraga Irri. Scheme");
		damsOfWestBengal.add("Patloi");
		damsOfWestBengal.add("Ramchandrapur");
		damsOfWestBengal.add("Rupai");
		damsOfWestBengal.add("Saharajore Irri. Scheme");
		damsOfWestBengal.add("Sali");
		damsOfWestBengal.add("Taragonia Irri. Scheme");
		damsOfWestBengal.add("Tatko");
		damsOfWestBengal.add("Teesta-III Lower");
		damsOfWestBengal.add("Teesta-IV Lower");
		damsOfWestBengal.add("Turga Irri. Scheme");
		damsOfWestBengal.add("Upper Dam: PPSP");
		
		Collection<String> totalDams=new ArrayList<String>();
		totalDams.addAll(damsOfKarntaka);
		totalDams.addAll(damsOfAndhraPradesh);
		totalDams.addAll(damsOfArunachalPradesh);
		totalDams.addAll(damsOfAssam);
		totalDams.addAll(damsOfBihar);
		totalDams.addAll(damsOfChattisgarh);
		totalDams.addAll(damsOfGoa);
		totalDams.addAll(damsOfGujarat);
		totalDams.addAll(damsOfHaryana);
		totalDams.addAll(damsOfHimachalPradesh);
		totalDams.addAll(damsOfJharkhand);
		totalDams.addAll(damsOfKerala);
		totalDams.addAll(damsOfMadhyaPradesh);
		totalDams.addAll(damsOfMaharashtra);
		totalDams.addAll(damsOfManipur);
		totalDams.addAll(damsOfMeghalaya);
		totalDams.addAll(damsOfMizoram);
		totalDams.addAll(damsOfNagaland);
		totalDams.addAll(damsOfWestBengal);
		totalDams.addAll(damsOfUttarPradesh);
		totalDams.addAll(damsOfuttarakhand);
		totalDams.addAll(damsOfTripura);
		totalDams.addAll(damsOfTelangana);
		totalDams.addAll(damsOfTamilNadu);
		totalDams.addAll(damsOfSikkim);
		totalDams.addAll(damsOfRajasthan);
		totalDams.addAll(damsOfPunjab);
		totalDams.addAll(damsOfOdisha);
		
		
		
		System.out.println(totalDams);
		
		Iterator<String> iterate=totalDams.iterator();
		System.out.println("====================Dam names starting with T======================");
		Iterator<String> iterator = totalDams.iterator();

		while (iterator.hasNext()) {
			String dam = (String) iterator.next();

			if (dam.startsWith("T")) {
				System.out.println("The dam name starting with T : " + dam);
			}

		}

		System.out.println(System.lineSeparator());
		System.out.println("====================Dam names ending with ra======================");
		Iterator<String> iterator1 = totalDams.iterator();
		while (iterator1.hasNext()) {
			String dam = (String) iterator1.next();

			if (dam.endsWith("ra")) {
				System.out.println("The dam name ending with ra : " + dam);
			}

		}

		System.out.println(System.lineSeparator());
		System.out.println("====================Dams name length more than 15======================");
		Iterator<String> iterator2 = totalDams.iterator();
		while (iterator2.hasNext()) {
			String dam = (String) iterator2.next();

			if (dam.length() >= 15) {
				System.out.println("dam name length more than 15 : " + dam);
			}

		}

		System.out.println(System.lineSeparator());
		System.out.println("====================Dam names in upperCase======================");
		Iterator<String> iterator6 = totalDams.iterator();
		while (iterator6.hasNext()) {
			String dam = (String) iterator6.next();
			String upperDam = dam.toUpperCase();

			if (upperDam.equals(dam)) {
				System.out.println("dam name in upperCase : " + dam);
			}

		}

		System.out.println(System.lineSeparator());
		System.out.println("====================Dam names in lowerCase======================");
		Iterator<String> iterator7 = totalDams.iterator();
		while (iterator7.hasNext()) {
			String dam = (String) iterator7.next();

			String lowerDam = dam.toLowerCase();

			if (lowerDam.equals(dam)) {

				System.out.println("dam name in lowerCase : " + dam);
			}

		}

		System.out.println(System.lineSeparator());
		System.out.println("====================checking for palindrome======================");
		Iterator<String> iterator3 = totalDams.iterator();
		while (iterator3.hasNext()) {

			String dam = (String) iterator3.next();
			int len = dam.length() - 1;
			int i, j, ch = 0;
			for (i = 0, j = len; i <= len; i++, j--) {
				if (dam.charAt(i) != dam.charAt(j)) {
					ch = 1;
					break;
				}
			}
			if (ch == 1) {

			} else {
				System.out.println("the dame name is planidrome : " + dam);
			}

		}

		System.out.println(System.lineSeparator());
		System.out.println("====================Dam names having letter p======================");
		System.out.println("size of collection before removing : " + totalDams.size());

		Iterator<String> iterator5 = totalDams.iterator();
		while (iterator5.hasNext()) {
			String dam = (String) iterator5.next();

			if (dam.contains("P") || dam.contains("p")) {
				System.out.println("removed dam name which contains p : " + dam);
				iterator5.remove();

			}

		}
		
		System.out.println("size of collection after removing : " + totalDams.size());
	}

}
